# Generated by Django 3.2.6 on 2021-08-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
